# Generated by Django 6.0.6 on 2026-06-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measure',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='area',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='thumbnail',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='youtube_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
